### ISSUE TITLE
WebApp

### ISSUE THREAD

**Issue by rafaelmluz** [innovationnorway/terraform-azurerm-web-app#2]
Hi @joakimhellum-in @najgel 

I'm analyzing the repostory code and after deploying it, I noticed that it's not really the Web App. This is the App Service.

Do you have any Web App deployment code?

Thank you
Rafael

**Comment by najgel** [comment]
Hi @rafaelmluz! 

Thanks for opening this! A web app is short for a "Azure App Service Web App", we have chosen not to use the full name in the repo, it is lengthy as it is. This module will create an app service of the type "web app", complete with an app service plan and autoscaling. 

For reference see: https://docs.microsoft.com/en-us/azure/app-service/app-service-web-overview and terraform documentation https://www.terraform.io/docs/providers/azurerm/r/app_service.html

If you instead are looking for deployment of code into an existing web app, this is not what this module does or tries to do.

I hope this made sense. Happy coding. =)

**Comment by rafaelmluz** [comment]
Hi @najgel 

I understood your point.

This code represents the building of the "Azure App Service Web App" and not "Azure API App", right?

Until then I had read in documentation on the Internet that it was not possible to create "Web App" via terraform.

It's possible to create ApiApp via terraform?

**Comment by najgel** [comment]
Hi @rafaelmluz,

that is correct, this module creates an "Azure App Service Web App". If you want to create an API app you must, as of today, use the azurerm_template_deployment resource and deploy an ARM template with an API app in it. You can see an example on https://github.com/innovationnorway/terraform-azurerm-api-app .

**Comment by rafaelmluz** [comment]
Hi!

Great! I need to use both cases.
You help-me much.

Thank you


Em sex, 7 de set de 2018 03:15, Niklas Gustafsson <notifications@github.com>
escreveu:
